name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name : install node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run : npm ci
      - name: Run tests
        run : npm test
name: deploy
  runs-on: ubuntu-latest
  steps:
      - name: buid project
        run : npm run build
      - name: deploy
        run: echo "deploying"

